baseurl = "http://example.org/"
title = "Hugo Website"
theme = "hugo-theme-nix"
languageCode = "en-us"
disqusShortname = "your_disqus_shortname"

[menu]
  [[menu.header]]
    name = "CV"
    weight = 2
    url = "/CV-Ann-2020.pdf"
  [[menu.header]]
    name = "About"
    weight = 1
    url = "/about"
  [[menu.header]]
    name = "experience"
    weight = 3
    url = "/experience"
    [[menu.header]]
    name = "Research"
    parent = "experience"
    weight = 1
    url = "/experience"
    [[menu.header]]
    name = "Teaching"
    parent = "experience"
    weight = 1
    url = "/experience"

[params]
  GithubID = "annwells"
  TwitterID = "Ann_E_Wells"
  LinkedInID = "annwellsphd"
  #GoogleplusID = "your_googleplus"
  #FacebookID = "your_facebook"
  #TelegramID = "your_telegram"
  Name = "Ann Wells"
  HeaderUsername = "ann"
  HeaderHostname = "jax"
  Email = "ann.wells@jax.org"
  About = "Hi! I'm Ann and this is my website. I am a postdoctoral associate at the Jackson Laboratory working with Dr. Gregory Carter. I am interested in developing new statistical tools and methods to integrate multi-omics data in an unbiased way. I am also interested in applying these methods to investigate complex diseases, particularly autoimmune diseases, and determine how gene by environment interact to develop disease. In addition to my research interests, I have a passion for data reproducibility and shareability, as well as empowering non-computational biologists to obtain the computational skills necessary to perform preliminary analyses on their own data. I do this through teaching and have also become a software carpentry instructor. When I'm not thinking about science I am often riding my bike on the beautiful park loop in Acadia National Park, going for hikes, working out, or generally enjoying the amazing island I live on."
  ProfilePicture = "/Ann.jpg"
  #Favicon = "/favicon.ico"
  SlackURL = "https://carterlabjax.slack.com"

